version: "3.9"

services:
  backend:
    build: ./backend
    container_name: campusforge-backend
    ports:
      - "8080:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - minio
    networks:
      - campusforge

  resume-worker:
    build: ./resume_worker
    container_name: campusforge-resume-worker
    env_file:
      - .env
    depends_on:
      - redis
      - minio
    networks:
      - campusforge

  redis:
    image: redis:7
    container_name: campusforge-redis
    ports:
      - "6379:6379"
    networks:
      - campusforge

  minio:
    image: minio/minio
    container_name: campusforge-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    networks:
      - campusforge

volumes:
  minio_data:

networks:
  campusforge:
    driver: bridge